export enum EAppContextConsts {
	SET_SCREEN_SIZE = 'SET_SCREEN_SIZE',
	SET_CURRENT_COLOR_MODE = 'SET_CURRENT_COLOR_MODE',
	SET_CURRENT_THEME_MODE = 'SET_CURRENT_THEME_MODE',
	SET_THEME_SETTINGS = 'SET_THEME_SETTINGS',
	SET_IS_MENU_ACTIVE = 'SET_IS_MENU_ACTIVE',
	SET_IS_CLICKED = 'SET_IS_CLICKED',
}
